name: music_playlist
description: "Music Playlist"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audio_metadata_extractor: ^0.0.4
  audio_service: ^0.18.15
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  go_router: ^14.4.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  rive_animated_icon: ^2.0.1
  uuid: ^4.5.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/musics/

flutter_gen:
  output: lib/generated/